import type { BuildingKey, BuildingDef } from '@/lib/game/types';

export const BUILDINGS: Record<BuildingKey, BuildingDef> = {
  woodcutter: {
    name: 'Woodcutter\'s Hut',
    icon: 'ic-woodcutter',
    desc: 'Harvests Wood from the forest.',
    baseCost: { gold: 15 },
    costScale: 1.15,
    baseProd: { wood: 1.2 },
    baseUse: {},
    maxLimit: 10,
  },
  quarry: {
    name: 'Quarry',
    icon: 'ic-quarry',
    desc: 'Extracts Stone from the mountains.',
    baseCost: { gold: 30, wood: 5 },
    costScale: 1.18,
    baseProd: { stone: 0.8 },
    baseUse: {},
    maxLimit: 8,
  },
  farm: {
    name: 'Farm',
    icon: 'ic-farm',
    desc: 'Grows Food to feed your people.',
    baseCost: { gold: 25, wood: 8 },
    costScale: 1.16,
    baseProd: { food: 1.5 },
    baseUse: {},
    maxLimit: 12,
  },
  blacksmith: {
    name: 'Blacksmith',
    icon: 'ic-blacksmith',
    desc: 'Crafts tools and weapons for Gold.',
    baseCost: { gold: 50, wood: 15, stone: 10 },
    costScale: 1.20,
    baseProd: { gold: 2.5 },
    baseUse: { wood: 0.3, stone: 0.2 },
    maxLimit: 6,
  },
  castle: {
    name: 'Castle',
    icon: 'ic-castle',
    desc: 'A grand fortress that generates Prestige.',
    baseCost: { gold: 200, wood: 50, stone: 100, food: 20 },
    costScale: 1.25,
    baseProd: { prestige: 0.1 },
    baseUse: { food: 0.5 },
    maxLimit: 3,
  },
  library: {
    name: 'Library',
    icon: 'ic-library',
    desc: 'A center of knowledge that generates research points.',
    baseCost: { gold: 100, wood: 30, stone: 20 },
    costScale: 1.22,
    baseProd: { gold: 1.0, researchPoints: 0.1 },
    baseUse: {},
    unlockConditions: [{ type: 'technology', key: 'writing', value: 1 }],
    maxLimit: 5,
  },
  university: {
    name: 'University',
    icon: 'ic-university',
    desc: 'Advanced education facility that boosts all production.',
    baseCost: { gold: 300, wood: 80, stone: 60, food: 30 },
    costScale: 1.28,
    baseProd: { gold: 3.0, prestige: 0.05, researchPoints: 0.3 },
    baseUse: { food: 1.0 },
    unlockConditions: [
      { type: 'technology', key: 'writing', value: 1 },
      { type: 'technology', key: 'mathematics', value: 1 }
    ],
    maxLimit: 2,
  },
  laboratory: {
    name: 'Laboratory',
    icon: 'ic-laboratory',
    desc: 'Research facility for advanced technologies.',
    baseCost: { gold: 500, wood: 100, stone: 150, food: 50 },
    costScale: 1.30,
    baseProd: { gold: 5.0, prestige: 0.1, researchPoints: 0.5 },
    baseUse: { food: 2.0 },
    unlockConditions: [
      { type: 'technology', key: 'chemistry', value: 1 },
      { type: 'technology', key: 'engineering', value: 1 }
    ],
    maxLimit: 1,
  },
  taxOffice: {
    name: 'Tax Office',
    icon: 'ic-tax-office',
    desc: 'Collects taxes from your citizens, generating gold income.',
    baseCost: { gold: 100, wood: 20, stone: 10 },
    costScale: 1.18,
    baseProd: { gold: 0.5 },
    baseUse: {},
    unlockConditions: [{ type: 'achievement', key: 'foodMaster' }],
    maxLimit: 4,
  },
};
