import type { TechnologyKey, TechnologyDef } from '../types';

export const TECHNOLOGIES: Record<TechnologyKey, TechnologyDef> = {
  writing: {
    name: 'Writing',
    icon: 'ic-writing',
    desc: 'The foundation of knowledge and communication.',
    baseCost: { gold: 50, wood: 20 },
    costScale: 1.0, // Technologies don't scale in cost
    researchTime: 30,
    unlocksBuildings: ['library'],
  },
  mathematics: {
    name: 'Mathematics',
    icon: 'ic-mathematics',
    desc: 'Advanced calculations and logical thinking.',
    baseCost: { gold: 100, wood: 30, stone: 20 },
    costScale: 1.0,
    researchTime: 60,
    unlocksBuildings: ['university'],
    requiresTech: ['writing'],
  },
  engineering: {
    name: 'Engineering',
    icon: 'ic-engineering',
    desc: 'Advanced construction and mechanical knowledge.',
    baseCost: { gold: 150, wood: 50, stone: 40 },
    costScale: 1.0,
    researchTime: 90,
    requiresTech: ['writing', 'mathematics'],
  },
  chemistry: {
    name: 'Chemistry',
    icon: 'ic-chemistry',
    desc: 'Understanding of materials and reactions.',
    baseCost: { gold: 200, wood: 60, stone: 50, food: 20 },
    costScale: 1.0,
    researchTime: 120,
    unlocksBuildings: ['laboratory'],
    requiresTech: ['mathematics', 'engineering'],
  },
  physics: {
    name: 'Physics',
    icon: 'ic-physics',
    desc: 'Laws of nature and energy.',
    baseCost: { gold: 300, wood: 80, stone: 70, food: 30 },
    costScale: 1.0,
    researchTime: 180,
    requiresTech: ['mathematics', 'chemistry'],
  },
  biology: {
    name: 'Biology',
    icon: 'ic-biology',
    desc: 'Study of life and living organisms.',
    baseCost: { gold: 400, wood: 100, stone: 90, food: 50 },
    costScale: 1.0,
    researchTime: 240,
    requiresTech: ['chemistry', 'physics'],
  },
};
